### ISSUE TITLE
配置META_PROVIDER环境变量的情况下，搜索错误

### ISSUE THREAD

**Issue by mwnu** [JeffersonQin/calibre-web-bgm#1]
在环境变量中设置数字也默认被当作字符串了。
```
500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/lsiopy/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/app/calibre-web/cps/search_metadata.py", line 141, in metadata_search
data.extend([asdict(x) for x in future.result() if x])
File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
return self.__get_result()
File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
raise self._exception
File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/app/calibre-web/cps/metadata_provider/bgm.py", line 63, in search
with multiprocessing.Pool(META_PROVIDER_BGM_THREAD_POOL) as pool:
File "/usr/lib/python3.10/multiprocessing/context.py", line 119, in Pool
return Pool(processes, initializer, initargs, maxtasksperchild,
File "/usr/lib/python3.10/multiprocessing/pool.py", line 204, in __init__
if processes < 1:
TypeError: '<' not supported between instances of 'str' and 'int'
Please report this issue with all related information:

```

**Comment by JeffersonQin** [comment]
已修复
